[package]
name = "document-proof-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
hex = "0.4.3"
reqwest = { version = "0.12.9", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
